### ISSUE TITLE
List IDが未チェック時でも、LISTアンカーに list:- がセットされてしまう

### ISSUE THREAD

**Issue by korei-xlix** [korei-xlix/website#14]
X検索保存ツールで、List IDが未チェック時でも、LISTアンカーに list:- がセットされてしまう。

テストもしてたはずだが、テスト時の確認漏れ、テストの方法にも問題がないか確認の必要がある。

**Comment by samafeald** [comment]
試験仕様書については、テキストベースで書いているが、パターンが非常に複雑なため、
組み合わせ漏れや、確認漏れがあったと思われる。
今後を考えて、テスト仕様書のテンプレートを作成することとする。

バグ確認、改修については、このテスト仕様書を書いたあとで実施することとする。（しばし時間がかかりそう）

**Comment by samafeald** [comment]
バグ対応完了。

URLリンク作成時、リンクIDのデフォルト値の比較値のデファイン参照をミスしてた"チープミス"。

なお、再試験は仕様書を作成せずに簡単に確認した。（1行修正のため）
